<?php

use Illuminate\Database\Seeder;

class PublicBeneficiariosValidados extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::statement(" INSERT INTO public.beneficiarios_validados(periodo,
 id_smiafiliadosaux,
 clavebeneficiario,
 afiapellido,
 afinombre,
 afitipodoc,
 aficlasedoc,
 afidni,
 afisexo,
 afitipocategoria,
 afifechanac,
 afideclaraindigena,
 afiid_lengua,
 afiid_tribu,
 matipodocumento,
 manrodocumento,
 maapellido,
 manombre,
 patipodocumento,
 panrodocumento,
 paapellido,
 panombre,
 otrotipodocumento,
 otronrodocumento,
 otroapellido,
 otronombre,
 otrotiporelacion,
 fechainscripcion,
 fechaaltaefectiva,
 fechadiagnosticoembarazo,
 semanasembarazo,
 fechaprobableparto,
 fechaefectivaparto,
 activo,
 afidomcalle,
 afidomnro,
 afidommanzana,
 afidompiso,
 afidomdepto,
 afidomentrecalle1,
 afidomentrecalle2,
 afidombarrioparaje,
 afidommunicipio,
 afidomdepartamento,
 afidomlocalidad,
 afidomprovincia,
 afidomcp,
 afitelefono,
 lugaratencionhabitual,
 datosfechaenvio,
 fechaalta,
 pendienteenviar,
 codigoprovinciaaltadatos,
 codigouadaltadatos,
 codigocialtadatos,
 motivobaja,
 mensajebaja,
 id_procesobajaautomatica,
 pendienteenviaranacion,
 id_procesoingresoafiliados,
 id_novedad,
 tiponovedad,
 fechanovedad,
 fechacarga,
 usuariocarga,
 aplicadoadefinitiva,
 fechabajaefectiva,
 mensajeproceso,
 clavebinaria,
 cuieefectorasignado,
 cuielugaratencionhabitual,
 clavebenefprovocobaja,
 idpersona,
 scorederiesgo,
 benefalfabetizacion,
 benefalfabetaniosultimonivel,
 madrealfabetizacion,
 madrealfabetaniosultimonivel,
 padrealfabetizacion,
 padrealfabetaniosultimonivel,
 tutoralfabetizacion,
 tutoralfabetaniosultimonivel,
 activor,
 motivobajar,
 mensajebajar,
 menorconvivecontutor,
 usuariocreacion,
 fechacreacion,
 email,
 numerocelular,
 fum,
 observacionesgenerales,
 discapacidad,
 afipais,
 embarazoactual,
 ceb,
 cuie,
 fechaultimaprestacion,
 codigoprestacion,
 devengacapita,
 devengacantidadcapita,
 grupopoblacional)
	 (
		SELECT *
		FROM dblink('dbname=sirge host=192.6.0.118 user=postgres password=PN2012$',
		    'SELECT periodo,
 id_smiafiliadosaux,
 clavebeneficiario,
 afiapellido,
 afinombre,
 afitipodoc,
 aficlasedoc,
 afidni,
 afisexo,
 afitipocategoria,
 afifechanac,
 afideclaraindigena,
 afiid_lengua,
 afiid_tribu,
 matipodocumento,
 manrodocumento,
 maapellido,
 manombre,
 patipodocumento,
 panrodocumento,
 paapellido,
 panombre,
 otrotipodocumento,
 otronrodocumento,
 otroapellido,
 otronombre,
 otrotiporelacion,
 fechainscripcion,
 fechaaltaefectiva,
 fechadiagnosticoembarazo,
 semanasembarazo,
 fechaprobableparto,
 fechaefectivaparto,
 activo,
 afidomcalle,
 afidomnro,
 afidommanzana,
 afidompiso,
 afidomdepto,
 afidomentrecalle1,
 afidomentrecalle2,
 afidombarrioparaje,
 afidommunicipio,
 afidomdepartamento,
 afidomlocalidad,
 afidomprovincia,
 afidomcp,
 afitelefono,
 lugaratencionhabitual,
 datosfechaenvio,
 fechaalta,
 pendienteenviar,
 codigoprovinciaaltadatos,
 codigouadaltadatos,
 codigocialtadatos,
 motivobaja,
 mensajebaja,
 id_procesobajaautomatica,
 pendienteenviaranacion,
 id_procesoingresoafiliados,
 id_novedad,
 tiponovedad,
 fechanovedad,
 fechacarga,
 usuariocarga,
 aplicadoadefinitiva,
 fechabajaefectiva,
 mensajeproceso,
 clavebinaria,
 cuieefectorasignado,
 cuielugaratencionhabitual,
 clavebenefprovocobaja,
 idpersona,
 scorederiesgo,
 benefalfabetizacion,
 benefalfabetaniosultimonivel,
 madrealfabetizacion,
 madrealfabetaniosultimonivel,
 padrealfabetizacion,
 padrealfabetaniosultimonivel,
 tutoralfabetizacion,
 tutoralfabetaniosultimonivel,
 activor,
 motivobajar,
 mensajebajar,
 menorconvivecontutor,
 usuariocreacion,
 fechacreacion,
 email,
 numerocelular,
 fum,
 observacionesgenerales,
 discapacidad,
 afipais,
 embarazoactual,
 ceb,
 cuie,
 fechaultimaprestacion,
 codigoprestacion,
 devengacapita,
 devengacantidadcapita,
 grupopoblacional 
			    FROM public.beneficiarios_validados LIMIT 100000')
		    AS sirge_beneficiarios_validados(periodo integer NOT NULL,
  id_smiafiliadosaux integer NOT NULL,
  clavebeneficiario character varying(16) NOT NULL,
  afiapellido character varying(50),
  afinombre character varying(50),
  afitipodoc character varying(5),
  aficlasedoc character(1),
  afidni character varying(12) NOT NULL,
  afisexo character(1),
  afitipocategoria smallint NOT NULL,
  afifechanac date NOT NULL,
  afideclaraindigena character(1),
  afiid_lengua integer,
  afiid_tribu integer,
  matipodocumento character varying(5),
  manrodocumento character varying(12),
  maapellido character varying(50),
  manombre character varying(50),
  patipodocumento character varying(5),
  panrodocumento character varying(12),
  paapellido character varying(50),
  panombre character varying(50),
  otrotipodocumento character varying(5),
  otronrodocumento character varying(12),
  otroapellido character varying(50),
  otronombre character varying(50),
  otrotiporelacion integer,
  fechainscripcion date,
  fechaaltaefectiva date,
  fechadiagnosticoembarazo date,
  semanasembarazo integer,
  fechaprobableparto date,
  fechaefectivaparto date,
  activo character(1),
  afidomcalle character varying(50),
  afidomnro character varying(5),
  afidommanzana character varying(3),
  afidompiso character varying(3),
  afidomdepto character varying(3),
  afidomentrecalle1 character varying(30),
  afidomentrecalle2 character varying(30),
  afidombarrioparaje character varying(40),
  afidommunicipio character varying(40),
  afidomdepartamento character varying(40),
  afidomlocalidad character varying(85),
  afidomprovincia character varying(20),
  afidomcp character varying(8),
  afitelefono character varying(20),
  lugaratencionhabitual character varying(80),
  datosfechaenvio date,
  fechaalta date,
  pendienteenviar smallint,
  codigoprovinciaaltadatos character(2),
  codigouadaltadatos character(3),
  codigocialtadatos character(5),
  motivobaja smallint,
  mensajebaja character varying(100),
  id_procesobajaautomatica integer,
  pendienteenviaranacion smallint,
  id_procesoingresoafiliados integer NOT NULL,
  id_novedad integer,
  tiponovedad character(1),
  fechanovedad date,
  fechacarga date,
  usuariocarga character varying(10),
  aplicadoadefinitiva smallint,
  fechabajaefectiva date,
  mensajeproceso character varying(100),
  clavebinaria character varying(70),
  cuieefectorasignado character varying(6),
  cuielugaratencionhabitual character varying(6),
  clavebenefprovocobaja character varying(16),
  idpersona bigint,
  scorederiesgo smallint,
  benefalfabetizacion character(2),
  benefalfabetaniosultimonivel smallint,
  madrealfabetizacion character(2),
  madrealfabetaniosultimonivel smallint,
  padrealfabetizacion character(2),
  padrealfabetaniosultimonivel smallint,
  tutoralfabetizacion character(2),
  tutoralfabetaniosultimonivel smallint,
  activor character(1),
  motivobajar smallint,
  mensajebajar character varying(150),
  menorconvivecontutor character(1),
  usuariocreacion character varying(15),
  fechacreacion date,
  email character varying(50),
  numerocelular character varying(20),
  fum date,
  observacionesgenerales text,
  discapacidad character(1),
  afipais character varying(40),
  embarazoactual character(1),
  ceb character(1),
  cuie character(14),
  fechaultimaprestacion date,
  codigoprestacion character varying(11),
  devengacapita character(1),
  devengacantidadcapita integer NOT NULL,
  grupopoblacional character(1))
	 )
        			   	");
    }
}
