--QUERY PARA CORRER EN EL MOTOR

--DROP SCHEMA aplicacion_fondos_old CASCADE;
DROP SCHEMA beneficiarios CASCADE;
DROP SCHEMA comprobantes CASCADE;
--DROP SCHEMA comprobantes_old CASCADE;
DROP SCHEMA compromiso_anual CASCADE;
DROP SCHEMA consultas CASCADE;
DROP SCHEMA ddjj CASCADE;
DROP SCHEMA efectores CASCADE;
DROP SCHEMA fondos CASCADE;
DROP SCHEMA geo CASCADE;
DROP SCHEMA indec CASCADE;
DROP SCHEMA indicadores CASCADE;
DROP SCHEMA logs CASCADE;
DROP SCHEMA mobile CASCADE;
DROP SCHEMA osp CASCADE;
DROP SCHEMA prestaciones CASCADE;
--DROP SCHEMA prestaciones_old CASCADE;
DROP SCHEMA profe CASCADE;
DROP SCHEMA pss CASCADE;
DROP SCHEMA puco CASCADE;
DROP SCHEMA sistema CASCADE;
DROP SCHEMA sss CASCADE;
DROP SCHEMA tmp CASCADE;
DROP SCHEMA trazadoras CASCADE;

TRUNCATE public.migrations;

--LUEGO DE EJECUTAR, VOLVER A CORRER 'php artisan migrate'