INSERT INTO diccionarios.diccionario values
(12,1,'id_provincia','character(2)','SI','Id que tiene la jurisdicción en el SIRGE.'),
(12,2,'Id_Prestación','integer','SI','Id que la jurisdicción le asigna a la prestación.'),
(12,3,'Codigo_Prestación','character varying(11)','SI','Según PSS. Prácticas complementarias de módulos quirúrgicos: deben reportarse como prestaciones independientes.'),
(12,4,'CUIE_Efector','character(6)','SI','Según tabla de efectoree'),
(12,5,'Fecha_Prestacion','date','SI','Fecha en la que la prestacion fue brindada'),
(12,6,'Apellido_Beneficiario','character varying(100)','SI','Apellido del beneficiario de la prestación.'),
(12,7,'Nombre_Beneficiario','character varying(100)','SI','Nombre del beneficiario de la prestación.'),
(12,8,'Clave_Beneficiario','character varying(16)','SI','Clave de beneficiario de quien recibe la prestación.'),
(12,9,'Benef_Tipo_Documento','character(3)','SI','Tipo de documento de quien recibe la prestación.'),
(12,10,'Benef_Clase_Documento','character(1)','SI','Clase de documento de quien recibe la prestación.'),
(12,11,'Benef_Nro_Documento','character varying(14)','SI','Número de documento de quien recibe la prestación.'),
(12,12,'Sexo','character(1)','SI','Sexo de quien recibe la prestación.'),
(12,13,'Fecha de Nacimiento','date','SI','Fecha de nacimiento de quien recibe la prestación.'),
(12,14,'Valor_Unitario_facturado','numeric(7,2)','SI','Precio unitario al que la prestación fue facturada.'),
(12,15,'Cantidad_facturada','integer','SI','Cantidad de unidades facturadas por esta prestación.'),
(12,16,'Importe_Prestacion_Facturado','numeric(9,2)','SI','Importe total facturado por esta prestación a*b.'),
(12,17,'id_factura','integer','SI','Id que la jurisdicción le asigna a la factura en la que está incluida la prestación.'),
(12,18,'numero_fact','integer','SI','Número de la factura en la que está incluida la prestación.'),
(12,19,'fecha_fact','date','SI','Fecha de generación de la factura en la que está incluida la prestación.'),
(12,20,'Importe_Total_Factura','numeric(9,2)','SI','Importe total de la factura en la que está incluida la prestación. Debe ser igual a la suma de Importe_Prestación_Facturado de todas las prestaciones con el mismo id_factura.'),
(12,21,'fecha_recepcion_fact','date','SI','Fecha de recepción por parte de la UG, independientemente de su recepción previa en otra dependencia del ministerio, de la factura en la que está incluida la prestación.'),
(12,22,'Alta complejidad','character(1)','SI','Si: prestación de alta complejidad según PPS - No: resto.'),
(12,23,'id_liquidacion','integer','SI','Id que la jurisdicción le asigna a la liquidación en la que está incluida la prestación.'),
(12,24,'fecha liquidacion','date','SI','Fecha en la que se generó la liquidación en la que está incluida la prestación.'),
(12,25,'Valor_Unitario_aprobado','numeric(7,2)','SI','Precio unitario al que la prestación fue aprobada por la UG.'),
(12,26,'Cantidad_aprobada','integer','SI','Cantidad de unidades por esta prestación aprobadas por la UG. En caso de que no la UG no apruebe ninguna prestación, este campo debe ser cero.'),
(12,27,'importe_Prestación_Aprobado','numeric(9,2)','SI','Importe total por esta prestación aprobado por la UG c*d.'),
(12,28,'id_dato_reportable_1','integer','SI','ID de dato reportable según RO - Anexo F'),
(12,29,'dato_reportable_1','character varying(255)','SI','Dato reportable respetando lo establecido en cuanto a tipo de dato y máscara según RO - Anexo F'),
(12,30,'id_dato_reportable_2','integer','SI','ID de dato reportable según RO - Anexo F'),
(12,31,'dato_reportable_2','character varying(255)','SI','Dato reportable respetando lo establecido en cuanto a tipo de dato y máscara según RO - Anexo F'),
(12,32,'id_dato_reportable_3','integer','SI','ID de dato reportable según RO - Anexo F'),
(12,33,'dato_reportable_3','character varying(255)','SI','Dato reportable respetando lo establecido en cuanto a tipo de dato y máscara según RO - Anexo F'),
(12,34,'id_dato_reportable_4','integer','SI','ID de dato reportable según RO - Anexo F'),
(12,35,'dato_reportable_4','character varying(255)','SI','Dato reportable respetando lo establecido en cuanto a tipo de dato y máscara según RO - Anexo F'),
(12,36,'id_op','integer','SI','Id que la jurisdicción le asigna a la OP en la que está incluida la prestación.'),
(12,37,'numero_op','integer','SI','Número de OP en la que está incluida la prestación.'),
(12,38,'fecha_op','date','SI','Fecha de generación de la OP en la que está incluida la prestación.'),
(12,39,'importe_total_op','numeric(7,2)','SI','Importe total de la OP en la que está incluida la prestación. Debería ser igual a la suma de importe_Prestación_Aprobado de todas las prestaciones correspondientes a los id_factura incluidos en la OP. Si hubiera una diferencia, ésta debe estar perfectamente identificada en el expte de pago que deberá estar disponible para las auditorías en terreno. Éstas diferencias pueden ser debido al traslado de débitos de la AETI a los efectores por ejemplo. Es decir que no corresponden a ajustes ni en la cantidad ni el valor unitario aprobados con respecto a los facturados'),
(12,40,'numero_expte','integer','SI','Número de expediente en el que está incluida toda la documentación que justifica el pago.'),
(12,41,'fecha_debito_bancario','date','SI','Fecha en la que se realizó el débito en la cuenta cápitas por el pago de la prestación al efector.'),
(12,42,'importe_debito_bancario','numeric(9,2)','SI','Importe total del débito bancario. Debe ser igual a la suma de importe_total_OP de todas las OP que se cancelan con esta transferencia.'),
(12,43,'fecha_notificacion_efector','date','SI','Fecha de notificación al efector de la transferencia. Obligatorio para efectores indirectos VER CAF OBLIGACIONES UG');
