CREATE MATERIALIZED VIEW efectores.mv_efectores_completo AS
 SELECT v_efectores_completo.cuie,
    v_efectores_completo.siisa,
    v_efectores_completo.nombre AS nombre_efector,
    v_efectores_completo.domicilio,
    v_efectores_completo.codigo_postal,
    v_efectores_completo.denominacion_legal,
    v_efectores_completo.id_tipo_efector,
    v_efectores_completo.sigla AS sigla_tipo,
    v_efectores_completo.tipo_efector_descripcion AS tipo_efector,
    v_efectores_completo.rural,
    v_efectores_completo.cics,
    v_efectores_completo.id_categorizacion,
    v_efectores_completo.cat_sigla AS sigla_categorizacion,
    v_efectores_completo.tipo_cat_descripcion AS categorizacion,
    v_efectores_completo.dependencia_sanitaria,
    v_efectores_completo.compromiso_gestion,
    v_efectores_completo.hcd,
    v_efectores_completo.sistema_hcd AS nombre_hce,
    v_efectores_completo.recupera_costos,
    v_efectores_completo.osp,
    v_efectores_completo.pami,
    v_efectores_completo.os_directo,
    v_efectores_completo.otro,
    v_efectores_completo.categoria_maternidad,
    v_efectores_completo.cumple_cone,
    v_efectores_completo.categoria_neonatologia,
    v_efectores_completo.opera_malformaciones,
    v_efectores_completo.categoria_cc,
    v_efectores_completo.categoria_iam,
    v_efectores_completo.red_flap,
    v_efectores_completo.id_provincia,
    v_efectores_completo.nombre_provincia,
    v_efectores_completo.indec_departamento,
    v_efectores_completo.nombre_departamento AS departamento,
    v_efectores_completo.indec_localidad,
    v_efectores_completo.nombre_localidad AS localidad,
    v_efectores_completo.ciudad,
    v_efectores_completo.latitud,
    v_efectores_completo.longitud,
    v_efectores_completo.internet,
    v_efectores_completo.factura_descentralizada,
    v_efectores_completo.factura_on_line AS factura_online,
    v_efectores_completo.numero_compromiso,
    v_efectores_completo.firmante AS firmante_compromiso,
    v_efectores_completo.fecha_suscripcion AS fecha_suscripcion_compromiso,
    v_efectores_completo.fecha_inicio AS fecha_inicio_compromiso,
    v_efectores_completo.fecha_fin AS fecha_fin_compromiso,
    v_efectores_completo.pago_indirecto,
    v_efectores_completo.numero_convenio,
    v_efectores_completo.convenio_firmante AS firmante_convenio,
    v_efectores_completo.nombre_tercer_administrador,
    v_efectores_completo.codigo_tercer_administrador,
    v_efectores_completo.convenio_fecha_suscripcion AS fecha_suscripcion_convenio,
    v_efectores_completo.convenio_fecha_inicio AS fecha_inicio_convenio,
    v_efectores_completo.convenio_fecha_fin AS fecha_fin_convenio,
    v_efectores_completo.email,
    v_efectores_completo.telefono
   FROM efectores.v_efectores_completo
  WITH NO DATA;
